### PR TITLE
search rss url created

### PR DESCRIPTION
**Pull request by adambournes21**
- in src/routes/feeds.js added an rss URL where the data about topics are read. This gives us a place to put info from searches where the front-end will read from
- also changed some of the front-end for categories.tpl in the NodeBB theme folder

### CODE REVIEW

**Review by juhyep — APPROVED** [review]
Looks good. I think we just need to continue implementing the display/UI portion of the search results so that we can use it to resolve other issues.

**Review by l-ma — APPROVED** [review]
Changes LGTM. We need to fix linter errors in next sprint.

**Comment by megchityala** [comment]
Looks good, will fix errors in next sprint

**Review by megchityala — APPROVED** [review]
This looks good, we can focus on fixing errors in our next sprint

**Pull request merged**
