### PR TITLE
Implement search bar

### PR DESCRIPTION
**Pull request by l-ma**
I added a "search" button and "related" topic tag. The search button which will be the onClick event that will search for related posts suing the related topic tag. Related posts will be based on the title of the posts. Currently has two versions of the search bar appearing on the frontend. I have to continue to test which one can be copied across all pages (current and future) and will then merge the buttons into one fully correct version in next sprint.

Makes progress on backlog item 1-1.

1543 tests passing locally; one test failing: "emailer plugin hook should work". I believe this is an internal NodeBB issue not related to changes I made. Will continue to debug.

### CODE REVIEW

**Review by juhyep — APPROVED** [review]
Changes look great, we can continue working on debugging to ensure that the code works properly

**Comment by megchityala** [comment]
Changes look good, we can continue working on implementation in our next sprint

**Comment by megchityala** [comment]
Changes look good, we can continue working on implementation in our next sprint

**Review by megchityala — APPROVED** [review]
Looks good, will focus more on implementation in sprint 2

**Review by adambournes21 — COMMENTED** [review]
seems good, we'll pass the linter next checkpoint

**Review by adambournes21 — APPROVED** [review]

**Pull request merged**
